### ISSUE TITLE
libgame.ScenarioConfig() can not be cannot be instantiated from Python (v1.4)

### ISSUE THREAD

**Issue by songhappy** [google-research/football#111]
Running v1.4 gives me an error of "class cannot be instantiated". Please see the error messages in details.

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/arda/intelWork/git/football/gfootball/play_game.py", line 66, in <module>
    app.run(main)
  File "/home/arda/.local/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/arda/.local/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/arda/intelWork/git/football/gfootball/play_game.py", line 49, in main
    'render': True
  File "/home/arda/intelWork/git/football/gfootball/env/config.py", line 120, in __init__
    self.NewScenario()
  File "/home/arda/intelWork/git/football/gfootball/env/config.py", line 187, in NewScenario
    self._scenario_cfg = scenario_builder.Scenario(self).ScenarioConfig()
  File "/home/arda/intelWork/git/football/gfootball/env/scenario_builder.py", line 52, in __init__
    self._scenario_cfg = libgame.ScenarioConfig()

**Comment by qstanczyk** [comment]
Can you provide some more details to reproduce the problem? Command line, environment used... Also, does it happen on HEAD?

**Comment by songhappy** [comment]
command line: MESA_GL_VERSION_OVERRIDE=3.2 MESA_GLSL_VERSION_OVERRIDE=150 python3 -m gfootball.play_game --players "ppo2_cnn:left_players=1,policy=gfootball_impala_cnn,checkpoint=$CHECKPOINT" --level=$LEVEL
environment, python3.7,  ubuntu 16.04, Intel® Core™ i7-6700 CPU.
Yes, it happened on HEAD

**Comment by qstanczyk** [comment]
Why do you need to run with "MESA_GL_VERSION_OVERRIDE=3.2 MESA_GLSL_VERSION_OVERRIDE=150"?
