### ISSUE TITLE
Run 11vs11 checkpoint cmd Error

### ISSUE THREAD

**Issue by yumianhuli2** [google-research/football#140]
Hello! There is a error by running 11vs11  trained PPO checkpoints.

python3 -m gfootball.play_game --players "ppo2_cnn:left_players=1,policy=gfootball_impala_cnn,checkpoint=./11" --level=1
2020-04-07 07:11:53.881449: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-04-07 07:11:53.885785: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2592000000 Hz
2020-04-07 07:11:53.886064: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x51d8a30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-04-07 07:11:53.886092: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-04-07 07:11:53.887110: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-04-07 07:11:53.887135: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2020-04-07 07:11:53.887148: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ubuntu): /proc/driver/nvidia/version does not exist
W0407 07:11:53.889157 139847482795840 module_wrapper.py:137] From /usr/local/lib/python3.6/dist-packages/baselines/common/input.py:31: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0407 07:11:53.889968 139847482795840 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/baselines/common/input.py:57: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/XXX/football/gfootball/play_game.py", line 70, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/XXX/football/gfootball/play_game.py", line 54, in main
    env = football_env.FootballEnv(cfg)
  File "/home/XXX/football/gfootball/env/football_env.py", line 46, in __init__
    self._players = self._construct_players(config['players'], player_config)
  File "/home/XXX/football/gfootball/env/football_env.py", line 78, in _construct_players
    player = player_factory.Player(player_config, self._config)
  File "/home/XXX/football/gfootball/env/players/ppo2_cnn.py", line 52, in __init__
    self._policy = policy_fn(nbatch=1, sess=self._sess)
  File "/usr/local/lib/python3.6/dist-packages/baselines/common/policies.py", line 142, in policy_fn
    policy_latent = policy_network(encoded_x)
  File "/home/XXX/football/gfootball/examples/models.py", line 38, in network_fn
    conv_out = snt.Conv2D(num_ch, 3, stride=1, padding='SAME')(conv_out)
  File "/usr/local/lib/python3.6/dist-packages/sonnet/src/base.py", line 126, in __call__
    module.__init__(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sonnet/src/conv.py", line 276, in __init__
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/sonnet/src/conv.py", line 77, in __init__
    super(ConvND, self).__init__(name=name)
  File "/usr/local/lib/python3.6/dist-packages/sonnet/src/base.py", line 411, in __init__
    assert_tf2()
  File "/usr/local/lib/python3.6/dist-packages/sonnet/src/base.py", line 372, in assert_tf2
    assert tf.executing_eagerly(), "Sonnet v2 requires TensorFlow 2"
AssertionError: Sonnet v2 requires TensorFlow 2

**Comment by vi3itor** [comment]
Please see my pull request #134 that was recently merged into master. You need to install Sonnet 1.36 by the running: 
`pip3 install "dm-sonnet<2.0.0"`
Please close the issue if it helps.

**Comment by yumianhuli2** [comment]
> Please see my pull request #134 that was recently merged into master. You need to install Sonnet 1.36 by running:
> `pip3 install "dm-sonnet<2.0.0"`
> Please close the issue if it helps.

OK I followed your steps and it helps,but new error occured.

python3 -m gfootball.play_game --players "ppo2_cnn:left_players=1,policy=gfootball_impala_cnn,checkpoint=11" --level=1
2020-04-08 00:52:50.492990: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-04-08 00:52:50.493165: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-04-08 00:52:50.493192: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
E0408 00:52:51.227118 139916840068928 football_env.py:73] Failed loading player "ppo2_cnn"
E0408 00:52:51.227539 139916840068928 football_env.py:74] No module named 'tensorflow.contrib'

**Comment by vi3itor** [comment]
@yumianhuli2 It's a problem with your TensorFlow installation. What is your TensorFlow version? This project requires to have version 1.15 installed. `pip3 install "tensorflow-gpu==1.15"`. 
And it's a good practice to use a virtual environment if you are running more than one project on your machine.  
Try searching for the error message, there are many discussions concerning this problem (like [this](https://github.com/tensorflow/tensorflow/issues/35968) one).

**Comment by yumianhuli2** [comment]
> @yumianhuli2 It's a problem with your TensorFlow installation. What is your TensorFlow version? This project requires to have version 1.15 installed. `pip3 install "tensorflow-gpu==1.15"`.
> And it's a good practice to use a virtual environment if you are running more than one project on your machine.
> Try searching for the error message, there are many discussions concerning this problem (like [this](https://github.com/tensorflow/tensorflow/issues/35968) one).

Python 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'1.15.0'
>>> exit()
And I  installed both tensorflow CPU and gpu version,so How can I uninstall the CPU version?

**Comment by vi3itor** [comment]
@yumianhuli2 Have you set up TensorFlow on your machine correctly? I think you should close the issue because it is not connected to the football project itself.
