### ISSUE TITLE
TypeError running PPO example

### ISSUE THREAD

**Issue by gekinci** [google-research/football#22]
Hi,
I am trying to run the example PPO experiment. I get the following error.

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gekinci/football/gfootball/examples/run_ppo2.py", line 112, in <module>
    train()
  File "/home/gekinci/football/gfootball/examples/run_ppo2.py", line 94, in train
    ], context=None)
TypeError: __init__() got an unexpected keyword argument 'context'

I simply tried removing that parameter but, then I get:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gekinci/football/gfootball/examples/run_ppo2.py", line 112, in <module>
    train()
  File "/home/gekinci/football/gfootball/examples/run_ppo2.py", line 108, in train
    cliprange=FLAGS.cliprange)
TypeError: learn() got an unexpected keyword argument 'network'

Thıs one I couldn't tackle in any way. 
Do you know how to fix this? Thanks in advance.

**Comment by cyfra** [comment]
Please check that you have a right version of "baselines" installed.

I've seen this error, when I've used the baselines from the pypi, rather than from github.
See #1 for details

**Comment by gekinci** [comment]
Hi Marcin. Thank you for your response. I did the installation exactly the way described in that issue, but still got baselines=0.1.5

**Comment by qstanczyk** [comment]
Is it possible that you had older version of baselines installed before? Could you try uninstalling it first?

**Comment by gekinci** [comment]
Yes, I tried reinstalling using the suggested ways [https://github.com/google-research/football/issues/1#issue-453546139](here) and also tried 'pip3 install baselines==0.1.6' and got the following:

Collecting baselines==0.1.6
  Could not find a version that satisfies the requirement baselines==0.1.6 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5)
No matching distribution found for baselines==0.1.6

**Comment by gekinci** [comment]
Yes, I tried reinstalling using the suggested ways [here](Yes, I tried reinstalling using the suggested ways https://github.com/google-research/football/issues/1#issue-453546139 and also tried 'pip3 install baselines==0.1.6' and got the following:

Collecting baselines==0.1.6
Could not find a version that satisfies the requirement baselines==0.1.6 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5)
No matching distribution found for baselines==0.1.6) and also tried 'pip3 install baselines==0.1.6' and got the following:

Collecting baselines==0.1.6
Could not find a version that satisfies the requirement baselines==0.1.6 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5)
No matching distribution found for baselines==0.1.6

**Comment by gekinci** [comment]
Yes, I tried reinstalling using the suggested ways [here](https://github.com/google-research/football/issues/1#issue-453546139) and also tried 'pip3 install baselines==0.1.6' and got the following:

Collecting baselines==0.1.6
Could not find a version that satisfies the requirement baselines==0.1.6 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5)
No matching distribution found for baselines==0.1.6

**Comment by cyfra** [comment]
The openAI baselines code was updated in github yesterday - and the version was increased to 0.1.6.

If you try to install from github now - you should get the 0.1.6
