### ISSUE TITLE
Cant seem to run create_environment 

### ISSUE THREAD

**Issue by AndrewRiceMGW** [google-research/football#304]
Hi I've tried to install gfootball following the steps for linux on my local machine and have not been able to create an environment using the create_environment function. Im using Ubuntu 20.04.3 LTS.  My script is as follows : 

```import gfootball.env as football_env

env = football_env.create_environment(
    env_name='academy_empty_goal', representation='pixels', render=True)

state = env.reset()

(base) ##@##-System-Product-Name:~/football$ /bin/python3 /home/###/football/train.py
Traceback (most recent call last):
  File "/home/####/football/train.py", line 1, in <module>
    import gfootball.env as football_env
  File "/home/###/football/gfootball/__init__.py", line 17, in <module>
    from gfootball.env import scenario_builder
  File "/home/###/football/gfootball/env/__init__.py", line 21, in <module>
    from gfootball.env import config
  File "/home/###/football/gfootball/env/config.py", line 27, in <module>
    import gfootball_engine as libgame
  File "/home/###/.local/lib/python3.8/site-packages/gfootball_engine/__init__.py", line 43, in <module>
    from _gameplayfootball import *
ImportError: libboost_filesystem.so.1.65.1: cannot open shared object file: No such file or directory```

Has anyone else had this issue and knows how to fix it?

**Comment by vi3itor** [comment]
The error indicates that you don't have `boost filesystem` library installed. Try reinstalling `boost` (specifically `boost filesystem`) or search for the specified file (`libboost_filesystem.so.1.65.1`). Try using wildcards to see what versions are installed on your system.

**Comment by AndrewRiceMGW** [comment]
> The error indicates that you don't have `boost filesystem` library installed. Try reinstalling `boost` (specifically `boost filesystem`) or search for the specified file (`libboost_filesystem.so.1.65.1`). Try using wildcards to see what versions are installed on your system.

I have these versions installed at the moment: 
````i A libboost-filesystem-dev                                                                        - filesystem operations (portable paths, iteration over directories, etc) in C++ (default version)        
p   libboost-filesystem-dev:i386                                                                   - filesystem operations (portable paths, iteration over directories, etc) in C++ (default version)        
p   libboost-filesystem1.67-dev                                                                    - filesystem operations (portable paths, iteration over directories, etc) in C++                          
p   libboost-filesystem1.67.0                                                                      - filesystem operations (portable paths, iteration over directories, etc) in C++                          
i A libboost-filesystem1.71-dev                                                                    - filesystem operations (portable paths, iteration over directories, etc) in C++                          
p   libboost-filesystem1.71-dev:i386                                                               - filesystem operations (portable paths, iteration over directories, etc) in C++                          
i A libboost-filesystem1.71.0                                                                      - filesystem operations (portable paths, iteration over directories, etc) in C++                          
p   libboost-filesystem1.71.0:i386  ````

The thing is I have the same versions installed on my laptop and following the same install instructions and it works I can run the environments. My desktop on the other hand, can only run the pre made examples but not allow me to set up  my own environment. I need to run it on my desktop because I have more RAM and GPU's available.
