### ISSUE TITLE
Windows10 can not run 'python -m gfootball.examples.run_ppo2 --level=academy_empty_goal_close'

### ISSUE THREAD

**Issue by fighting-zz** [google-research/football#326]
C:\dev\football\football-env\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\dev\football\football-env\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\dev\football\football-env\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\dev\football\football-env\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\dev\football\football-env\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\dev\football\football-env\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\dev\football\football-env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\dev\football\football-env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\dev\football\football-env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\dev\football\football-env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\dev\football\football-env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\dev\football\football-env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\dev\football\football-env\lib\site-packages\sonnet\python\custom_getters\restore_initializer.py:27: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\dev\football\gfootball\examples\run_ppo2.py", line 121, in <module>
    app.run(train)
  File "C:\dev\football\football-env\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\dev\football\football-env\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "C:\dev\football\gfootball\examples\run_ppo2.py", line 90, in train
    ], context=None)
  File "C:\dev\football\baselines\common\vec_env\subproc_vec_env.py", line 66, in __init__
    p.start()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\dev\football\baselines\common\vec_env\vec_env.py", line 200, in __getstate__
    return cloudpickle.dumps(self.x)
  File "C:\dev\football\football-env\lib\site-packages\cloudpickle\cloudpickle.py", line 1125, in dumps
    cp.dump(obj)
  File "C:\dev\football\football-env\lib\site-packages\cloudpickle\cloudpickle.py", line 482, in dump
    return Pickler.dump(self, obj)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 437, in dump
    self.save(obj)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 789, in save_tuple
    save(element)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 819, in save_list
    self._batch_appends(obj)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 846, in _batch_appends
    save(tmp[0])
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\dev\football\football-env\lib\site-packages\cloudpickle\cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "C:\dev\football\football-env\lib\site-packages\cloudpickle\cloudpickle.py", line 758, in save_function_tuple
    save(state)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 890, in _batch_setitems
    save(v)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\dev\football\football-env\lib\site-packages\cloudpickle\cloudpickle.py", line 556, in save_function
    return self.save_function_tuple(obj)
  File "C:\dev\football\football-env\lib\site-packages\cloudpickle\cloudpickle.py", line 758, in save_function_tuple
    save(state)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 524, in save
    rv = reduce(self.proto)
  File "C:\dev\football\football-env\lib\site-packages\absl\flags\_flagvalues.py", line 657, in __getstate__
    raise TypeError("can't pickle FlagValues")
TypeError: can't pickle FlagValues
Exception ignored in: <function SubprocVecEnv.__del__ at 0x0000016A57B5E1F8>
Traceback (most recent call last):
  File "C:\dev\football\baselines\common\vec_env\subproc_vec_env.py", line 121, in __del__
  File "C:\dev\football\baselines\common\vec_env\vec_env.py", line 98, in close
  File "C:\dev\football\baselines\common\vec_env\subproc_vec_env.py", line 106, in close_extras
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 139, in join
AssertionError: can only join a started process

(football-env) C:\dev\football>C:\dev\football\football-env\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\dev\football\football-env\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\dev\football\football-env\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\dev\football\football-env\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\dev\football\football-env\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\dev\football\football-env\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\dev\football\football-env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\dev\football\football-env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\dev\football\football-env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\dev\football\football-env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\dev\football\football-env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\dev\football\football-env\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

WARNING:tensorflow:From C:\dev\football\football-env\lib\site-packages\sonnet\python\custom_getters\restore_initializer.py:27: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

my pip list:
absl-py                1.2.0
astor                  0.8.1
baselines              0.1.6     c:\dev\football\baselines
cachetools             4.2.4
certifi                2022.6.15
charset-normalizer     2.1.0
click                  8.1.3
cloudpickle            1.2.2
colorama               0.4.5
contextlib2            21.6.0
decorator              5.1.1
dm-sonnet              1.23
dm-tree                0.1.7
future                 0.18.2
gast                   0.2.2
gfootball              2.10.3
google-auth            1.35.0
google-auth-oauthlib   0.4.6
google-pasta           0.2.0
grpcio                 1.47.0
gym                    0.15.7
gym-notices            0.0.7
h5py                   2.10.0
idna                   3.3
importlib-metadata     4.12.0
joblib                 1.1.0
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.2
Markdown               3.4.1
numpy                  1.18.5
oauthlib               3.2.0
opencv-python          4.6.0.66
opt-einsum             3.3.0
pip                    22.1.2
protobuf               3.20.1
psutil                 5.9.1
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pygame                 2.1.2
pyglet                 1.5.0
requests               2.28.1
requests-oauthlib      1.3.1
rsa                    4.9
scipy                  1.7.3
semantic-version       2.10.0
setuptools             63.2.0
six                    1.16.0
tensorboard            1.14.0
tensorflow             1.14.0
tensorflow-estimator   1.14.0
tensorflow-probability 0.7.0
termcolor              1.1.0
tqdm                   4.64.0
typing_extensions      4.3.0
urllib3                1.26.10
Werkzeug               2.1.2
wheel                  0.37.1
wrapt                  1.14.1
zipp                   3.8.1

**Comment by zdvlp** [comment]
same issue on windows
