### ISSUE TITLE
Installation problem with gfootball on Python 3.10 Conda environment

### ISSUE THREAD

**Issue by neuronphysics** [google-research/football#363]
Hi,

I've been attempting to set up the gfootball environment within a Conda environment that already included other multi-agent systems requiring Python 3.10. I've encountered difficulties while trying to install gfootball from source.

Steps to Reproduce:

-     Clone the gfootball repository.
-     Run pip install -e .

 The installation process results in a series of errors.

Error Log:
```
pip install -e .
Obtaining file:///home/zsheikhb/MARL/master/football
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pygame>=1.9.6 in /home/.conda/envs/marl/lib/python3.10/site-packages (from gfootball==2.9) (2.5.1)
Requirement already satisfied: opencv-python in /home/.conda/envs/marl/lib/python3.10/site-packages (from gfootball==2.9) (4.8.0.76)
Requirement already satisfied: psutil in /home/.conda/envs/marl/lib/python3.10/site-packages (from gfootball==2.9) (5.9.5)
Requirement already satisfied: scipy in /home/.conda/envs/marl/lib/python3.10/site-packages (from gfootball==2.9) (1.11.2)
Requirement already satisfied: gym>=0.11.0 in /home/.conda/envs/marl/lib/python3.10/site-packages (from gfootball==2.9) (0.26.2)
Requirement already satisfied: absl-py in /home/.conda/envs/marl/lib/python3.10/site-packages (from gfootball==2.9) (1.4.0)
Requirement already satisfied: wheel in /home/.conda/envs/marl/lib/python3.10/site-packages (from gfootball==2.9) (0.41.2)
Requirement already satisfied: numpy>=1.18.0 in /home/.conda/envs/marl/lib/python3.10/site-packages (from gym>=0.11.0->gfootball==2.9) (1.24.3)
Requirement already satisfied: cloudpickle>=1.2.0 in /home/.conda/envs/marl/lib/python3.10/site-packages (from gym>=0.11.0->gfootball==2.9) (2.2.1)
Requirement already satisfied: gym-notices>=0.0.4 in /home/.conda/envs/marl/lib/python3.10/site-packages (from gym>=0.11.0->gfootball==2.9) (0.0.8)
Installing collected packages: gfootball
  Attempting uninstall: gfootball
    Found existing installation: gfootball 2.9
    Can't uninstall 'gfootball'. No files were found to uninstall.
  Running setup.py develop for gfootball
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [92 lines of output]
        running develop
        /home/.conda/envs/marl/lib/python3.10/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` and ``easy_install``.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://github.com/pypa/setuptools/issues/917 for details.
                ********************************************************************************
        
        !!
          easy_install.initialize_options(self)
        /home/.conda/envs/marl/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
        !!
        
                ********************************************************************************
                Please avoid running ``setup.py`` directly.
                Instead, use pypa/build, pypa/installer or other
                standards-based tools.
        
                See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
                ********************************************************************************
        
        !!
          self.initialize_options()
        running egg_info
        writing gfootball.egg-info/PKG-INFO
        writing dependency_links to gfootball.egg-info/dependency_links.txt
        writing requirements to gfootball.egg-info/requires.txt
        writing top-level names to gfootball.egg-info/top_level.txt
        reading manifest file 'gfootball.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        adding license file 'LICENSE'
        writing manifest file 'gfootball.egg-info/SOURCES.txt'
        running build_ext
        ~/MARL/master/football/third_party/gfootball_engine ~/MARL/master/football
        -- The C compiler identification is GNU 9.4.0
        -- The CXX compiler identification is GNU 9.4.0
        -- Check for working C compiler: /usr/bin/cc
        -- Check for working C compiler: /usr/bin/cc -- works
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- Check for working CXX compiler: /usr/bin/c++
        -- Check for working CXX compiler: /usr/bin/c++ -- works
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
          Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
          available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
          cmake_policy command to set the policy and suppress this warning.
        
          FindOpenGL found both a legacy GL library:
        
            OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
        
          and GLVND libraries for OpenGL and GLX:
        
            OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
            OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
        
          OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
          compatibility with CMake 3.10 and below the legacy GL library will be used.
        Call Stack (most recent call first):
          CMakeLists.txt:24 (FIND_PACKAGE)
        This warning is for project developers.  Use -Wno-dev to suppress it.
        
        -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
        -- Found EGL: /usr/lib/x86_64-linux-gnu/libEGL.so
        -- Found SDL2_image: /usr/lib/x86_64-linux-gnu/libSDL2_image.so
        -- Found SDL2_ttf: /usr/lib/x86_64-linux-gnu/libSDL2_ttf.so
        -- Found SDL2_gfx: /usr/lib/x86_64-linux-gnu/libSDL2_gfx.so (found version "1.0.4")
        -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found suitable version "3.8.10", minimum required is "3")
        Using Python: 3.8.10
        -- Could NOT find Boost: missing: python3-py38 (found /home/.conda/envs/marl/lib/cmake/Boost-1.73.0/BoostConfig.cmake (found version "1.73.0"))
        python3-py38 not found. Trying other names.
        -- Could NOT find Boost: missing: python-py38 (found /home/conda/envs/marl/lib/cmake/Boost-1.73.0/BoostConfig.cmake (found version "1.73.0"))
        python-py38 not found. Trying other names.
        -- Could NOT find Boost: missing: python38 (found /home/conda/envs/marl/lib/cmake/Boost-1.73.0/BoostConfig.cmake (found version "1.73.0"))
        CMake Error at CMakeLists.txt:70 (message):
          Python boost not found
        
        
        -- Configuring incomplete, errors occurred!
        See also "/home/zsheikhb/MARL/master/football/third_party/gfootball_engine/CMakeFiles/CMakeOutput.log".
        gfootball/build_game_engine.sh: line 29: pushd: third_party/gfootball_engine: No such file or directory
        error: Google Research Football compilation failed
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Can't roll back gfootball; was not uninstalled
error: subprocess-exited-with-error

× python setup.py develop did not run successfully.
│ exit code: 1
╰─> [92 lines of output]
    running develop
    /home/.conda/envs/marl/lib/python3.10/site-packages/setuptools/command/develop.py:40: EasyInstallDeprecationWarning: easy_install command is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` and ``easy_install``.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://github.com/pypa/setuptools/issues/917 for details.
            ********************************************************************************
    
    !!
      easy_install.initialize_options(self)
    /home/.conda/envs/marl/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
    !!
    
            ********************************************************************************
            Please avoid running ``setup.py`` directly.
            Instead, use pypa/build, pypa/installer or other
            standards-based tools.
    
            See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
            ********************************************************************************
    
    !!
      self.initialize_options()
    running egg_info
    writing gfootball.egg-info/PKG-INFO
    writing dependency_links to gfootball.egg-info/dependency_links.txt
    writing requirements to gfootball.egg-info/requires.txt
    writing top-level names to gfootball.egg-info/top_level.txt
    reading manifest file 'gfootball.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    writing manifest file 'gfootball.egg-info/SOURCES.txt'
    running build_ext
    ~/MARL/master/football/third_party/gfootball_engine ~/MARL/master/football
    -- The C compiler identification is GNU 9.4.0
    -- The CXX compiler identification is GNU 9.4.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Warning (dev) at /usr/share/cmake-3.16/Modules/FindOpenGL.cmake:275 (message):
      Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
      available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
      cmake_policy command to set the policy and suppress this warning.
    
      FindOpenGL found both a legacy GL library:
    
        OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so
    
      and GLVND libraries for OpenGL and GLX:
    
        OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
        OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so
    
      OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
      compatibility with CMake 3.10 and below the legacy GL library will be used.
    Call Stack (most recent call first):
      CMakeLists.txt:24 (FIND_PACKAGE)
    This warning is for project developers.  Use -Wno-dev to suppress it.
    
    -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    -- Found EGL: /usr/lib/x86_64-linux-gnu/libEGL.so
    -- Found SDL2_image: /usr/lib/x86_64-linux-gnu/libSDL2_image.so
    -- Found SDL2_ttf: /usr/lib/x86_64-linux-gnu/libSDL2_ttf.so
    -- Found SDL2_gfx: /usr/lib/x86_64-linux-gnu/libSDL2_gfx.so (found version "1.0.4")
    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found suitable version "3.8.10", minimum required is "3")
    Using Python: 3.8.10
    -- Could NOT find Boost: missing: python3-py38 (found /home/.conda/envs/marl/lib/cmake/Boost-1.73.0/BoostConfig.cmake (found version "1.73.0"))
    python3-py38 not found. Trying other names.
    -- Could NOT find Boost: missing: python-py38 (found /home/.conda/envs/marl/lib/cmake/Boost-1.73.0/BoostConfig.cmake (found version "1.73.0"))
    python-py38 not found. Trying other names.
    -- Could NOT find Boost: missing: python38 (found /home/.conda/envs/marl/lib/cmake/Boost-1.73.0/BoostConfig.cmake (found version "1.73.0"))
    CMake Error at CMakeLists.txt:70 (message):
      Python boost not found
    
    
    -- Configuring incomplete, errors occurred!
    See also "/home/MARL/master/football/third_party/gfootball_engine/CMakeFiles/CMakeOutput.log".
    gfootball/build_game_engine.sh: line 29: pushd: third_party/gfootball_engine: No such file or directory
    error: Google Research Football compilation failed
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
```
I observed that 

- Errors related to missing Boost libraries for Python 3.8 (python3-py38, python-py38, python38).
- There's a mention of Python 3.8.10 in the logs, although my environment is based on Python 3.10. This could be a potential version mismatch issue.

Would you suggest a way to deal with this installation issue ?

**Comment by Hitsuzen-maker** [comment]
have you solved this problem?

**Comment by Jackory** [comment]
Same problem for me

**Comment by TitiSkywalker** [comment]
I solved this a long time ago in Windows 11 and sadly do not remember how I did it. I have a vague impression that we need to first install **vcpkg** and **cmake**, then set **VCPKG_ROOT** in the system environment correctly. 

After solving this issue, you will encounter more problems related to package version. According to my diary, we next need to run
```
pip install pygame==2.1.2
pip install --upgrade pip setuptools==57.5.0
python -m pip install pip==20.0.1
pip install gym==0.20.0
```
This is because we need to use the old **gym** interface. To install the old gym, we need to install the old **pip** and **setuptools**. 

I hope my partial information will help you.

**Comment by Sic4rioDragon** [comment]
> I solved this a long time ago in Windows 11 and sadly do not remember how I did it. I have a vague impression that we need to first install **vcpkg** and **cmake**, then set **VCPKG_ROOT** in the system environment correctly.
> 
> After solving this issue, you will encounter more problems related to package version. According to my diary, we next need to run
> 
> ```
> pip install pygame==2.1.2
> pip install --upgrade pip setuptools==57.5.0
> python -m pip install pip==20.0.1
> pip install gym==0.20.0
> ```
> 
> This is because we need to use the old **gym** interface. To install the old gym, we need to install the old **pip** and **setuptools**.
> 
> I hope my partial information will help you.


i always get C:\Users\sic4r>pip install gym==0.20.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python313\Scripts\pip.exe\__main__.py", line 4, in <module>
    from pip._internal.cli.main import main
  File "C:\Python313\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Python313\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Python313\Lib\site-packages\pip\_internal\cli\main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "C:\Python313\Lib\site-packages\pip\_internal\cli\cmdoptions.py", line 19, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'
no mater what version i try

**Comment by TitiSkywalker** [comment]
Perhaps your Python version is too new. I was using Python 3.10.15.

**Comment by skr3178** [comment]
i can compile on python 3.10
```To install create python env 3.10 on conda running
conda create -y -n gfootball310 python=3.10
conda create -y -n gfootball310 python=3.10

Then run the following commands:

sudo apt-get install git cmake build-essential libgl1-mesa-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libboost-all-dev libdirectfb-dev libst-dev mesa-utils xvfb x11vnc python3-pip

downgrade setuptools to install gym

pip3 install setuptools==65.5.0
pip install -r requirements.txt 

Then upgrade again to install gfootball
python3 -m pip install --upgrade pip setuptools psutil wheel
python3 -m pip install .

Update the GCC 
conda install -c conda-forge libstdcxx-ng

python3 -m gfootball.play_game --action_set=full

sudo apt-get install -y gcc-10 g++-10
sudo apt-get install -y libstdc++6
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX

python3 -m gfootball.play_game --action_set=full

How is reward function designed?

```
However, i need to compile on 3.7 to run the ppo.

**Comment by BingwenDong** [comment]
The failure is due to the installation process includes running a shell script (build_game_engine.sh). This script uses a Python one-liner to import psutil and determine the number of parallel compilation jobs based on available CPU cores and memory. If the import fails, the entire build halts with an import error. 
Even if you're using a virtual environment, the script **tend to use system-wide Python** (e.g., `/usr/bin/python3`). 

SOLUTION:

First clone the repo. You need to download the reliances. Next go into the folder.

Run `/usr/bin/python3 -c "import psutil"` and `pip install gfootball` will solve the problem.
