### ISSUE TITLE
How can solve RuntimeError: Dynamic linking causes SDL downgrade! (compiled with version 2.28.3, linked to 2.0.16)?

### ISSUE THREAD

**Issue by hancruyff** [google-research/football#365]
I'm using anaconda environment with python3.7
but this error happened
D:\ref>python -m gfootball.play_game --action_set=full
Traceback (most recent call last):
  File "C:\Users\hanji\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\hanji\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\hanji\AppData\Local\Programs\Python\Python310\lib\site-packages\gfootball\play_game.py", line 71, in <module>
    app.run(main)
  File "C:\Users\hanji\AppData\Local\Programs\Python\Python310\lib\site-packages\absl\app.py", line 308, in run
    _run_main(main, args)
  File "C:\Users\hanji\AppData\Local\Programs\Python\Python310\lib\site-packages\absl\app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "C:\Users\hanji\AppData\Local\Programs\Python\Python310\lib\site-packages\gfootball\play_game.py", line 55, in main
    env = football_env.FootballEnv(cfg)
  File "C:\Users\hanji\AppData\Local\Programs\Python\Python310\lib\site-packages\gfootball\env\football_env.py", line 47, in __init__
    self._players = self._construct_players(config['players'], player_config)
  File "C:\Users\hanji\AppData\Local\Programs\Python\Python310\lib\site-packages\gfootball\env\football_env.py", line 71, in _construct_players
    player_factory = importlib.import_module(
  File "C:\Users\hanji\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\hanji\AppData\Local\Programs\Python\Python310\lib\site-packages\gfootball\env\players\keyboard.py", line 18, in <module>
    import pygame
  File "C:\Users\hanji\AppData\Local\Programs\Python\Python310\lib\site-packages\pygame\__init__.py", line 92, in <module>
    from pygame.base import *  # pylint: disable=wildcard-import; lgtm[py/polluting-import]
RuntimeError: Dynamic linking causes SDL downgrade! (compiled with version 2.28.3, linked to 2.0.16)

how can I solve this problem?
I tried pygame upgrade and uninstall and install too.

**Comment by andre-vd** [comment]
If you go into the folder where your packages are installed and search for SDL2.dll, you'll see two different SDL2.dll files. One instance in pygame and another in the GFootball package. Go to the properties of the files to see which one is version 2.28.3, and replace the older version with that version.

**Comment by emirusahin** [comment]
andre_vd saves lives
