### ISSUE TITLE
ImportError: /../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found

### ISSUE THREAD

**Issue by CarlossShi** [google-research/football#366]
- System: WSL, Ubuntu 22.04.2 LTS
- Python 3.7.17, 3.8.18, 3.9.18

Reproduce:
```
conda create -n football python=3.8
conda activate football
```
```
sudo apt-get install git cmake build-essential libgl1-mesa-dev libsdl2-dev \
libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libboost-all-dev \
libdirectfb-dev libst-dev mesa-utils xvfb x11vnc python3-pip
```
```
python3 -m pip install --upgrade pip setuptools psutil wheel
python3 -m pip install gfootball
```
```
python3 -m gfootball.play_game --action_set=full
```
And then I got the error below:
```
libgame.so _gameplayfootball.so && popd
Traceback (most recent call last):
  File "/home/carlos/anaconda3/envs/football/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/carlos/anaconda3/envs/football/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/carlos/anaconda3/envs/football/lib/python3.8/site-packages/gfootball/__init__.py", line 17, in <module>
    from gfootball.env import scenario_builder
  File "/home/carlos/anaconda3/envs/football/lib/python3.8/site-packages/gfootball/env/__init__.py", line 21, in <module>
    from gfootball.env import config
  File "/home/carlos/anaconda3/envs/football/lib/python3.8/site-packages/gfootball/env/config.py", line 27, in <module>
    import gfootball_engine as libgame
  File "/home/carlos/anaconda3/envs/football/lib/python3.8/site-packages/gfootball_engine/__init__.py", line 43, in <module>
    from _gameplayfootball import *
ImportError: /home/carlos/anaconda3/envs/football/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/carlos/anaconda3/envs/football/lib/python3.8/site-packages/gfootball_engine/_gameplayfootball.so)
```

I've tried methods suggested in ['GLIBCXX_3.4.30' not found for librosa in conda virtual environment (after trying out a lot of solutions)?](https://stackoverflow.com/a/74533050/12224183), [Anaconda ImportError: /usr/lib64/libstdc++.so.6: version GLIBCXX_3.4.21 not found](https://stackoverflow.com/a/74132234/12224183): `conda install -c conda-forge libstdcxx-ng=12` and `conda install -c conda-forge libstdcxx-ng`, respectively.

However, I get another error:
```
libgame.so _gameplayfootball.so && popd
Traceback (most recent call last):
  File "/home/carlos/anaconda3/envs/football/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/carlos/anaconda3/envs/football/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/carlos/anaconda3/envs/football/lib/python3.8/site-packages/gfootball/__init__.py", line 17, in <module>
    from gfootball.env import scenario_builder
  File "/home/carlos/anaconda3/envs/football/lib/python3.8/site-packages/gfootball/env/__init__.py", line 21, in <module>
    from gfootball.env import config
  File "/home/carlos/anaconda3/envs/football/lib/python3.8/site-packages/gfootball/env/config.py", line 27, in <module>
    import gfootball_engine as libgame
  File "/home/carlos/anaconda3/envs/football/lib/python3.8/site-packages/gfootball_engine/__init__.py", line 43, in <module>
    from _gameplayfootball import *
SystemError: initialization of _gameplayfootball raised unreported exception
```

Would you please help me solve the problem? Thanks!

**Comment by qq591822071** [comment]
I have a similar problem, and my error message is
Traceback (most recent call last):
  File "/home/yuechao/anaconda3/envs/grf/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/yuechao/anaconda3/envs/grf/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/yuechao/anaconda3/envs/grf/lib/python3.9/site-packages/gfootball/__init__.py", line 17, in <module>
    from gfootball.env import scenario_builder
  File "/home/yuechao/anaconda3/envs/grf/lib/python3.9/site-packages/gfootball/env/__init__.py", line 21, in <module>
    from gfootball.env import config
  File "/home/yuechao/anaconda3/envs/grf/lib/python3.9/site-packages/gfootball/env/config.py", line 27, in <module>
    import gfootball_engine as libgame
  File "/home/yuechao/anaconda3/envs/grf/lib/python3.9/site-packages/gfootball_engine/__init__.py", line 43, in <module>
    from _gameplayfootball import *
ImportError: /lib/x86_64-linux-gnu/libwayland-client.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0
Hope to receive a reply

**Comment by Tingz0** [comment]
I encounter the same issues. Anyone solve this?

**Comment by ValkyrieMashiro** [comment]
Same issue.
`(grf) zxh@ubuntu-AS-4124GS-TNR:~$ python3 -m gfootball.play_game --action_set=full
Traceback (most recent call last):
  File "/home/zxh/anaconda3/envs/grf/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/zxh/anaconda3/envs/grf/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/zxh/anaconda3/envs/grf/lib/python3.8/site-packages/gfootball/__init__.py", line 17, in <module>
    from gfootball.env import scenario_builder
  File "/home/zxh/anaconda3/envs/grf/lib/python3.8/site-packages/gfootball/env/__init__.py", line 21, in <module>
    from gfootball.env import config
  File "/home/zxh/anaconda3/envs/grf/lib/python3.8/site-packages/gfootball/env/config.py", line 27, in <module>
    import gfootball_engine as libgame
  File "/home/zxh/anaconda3/envs/grf/lib/python3.8/site-packages/gfootball_engine/__init__.py", line 43, in <module>
    from _gameplayfootball import *
SystemError: initialization of _gameplayfootball raised unreported exception
`

**Comment by TitiSkywalker** [comment]
## How to solve this issue
I have solved this problem in Ubuntu,  miniconda3. First, you need to check whether your system has the correct version of "GLIBCXX". You can do this by running:
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
```
This should display a list of GLIBCXX versions. You need to check whether you have GLIBCXX 3.4.30. If it exists, you can proceed to the next step. Otherwise you probably need to update your system.

Next, check what's wrong with your conda environment by running:
```
strings /path_to_your_environment/lib/libstdc++.so.6  | grep GLIBC
```
In my case, conda only has GLIBCXX 3.4.29. This is why it doesn't work. We then need to link the library. We can run:
```
ln -sf /usr/lib/x86_64-linux-gnu/libstdc++.so.6 /path_to_your_environment/lib/libstdc++.so.6
```

After doing this, the engine can be compiled. (For me, I need to run "pip install six" before it works).

## Other problems you might encounter
Here are other information you might need. This package is old, so we need to install older version of **gym**. To do this, we need the older versioins of **pygame**,  **pip** and **setuptools**. Try running:
```
pip install pygame==2.1.2
pip install --upgrade pip setuptools==57.5.0
python -m pip install pip==20.0.1
pip install gym==0.20.0
```

**Comment by Toandinh1** [comment]
who solved it? please guide me :(
