### ISSUE TITLE
Can not find e_BackendAction in python

### ISSUE THREAD

**Issue by lezard618** [google-research/football#37]
python3 -m gfootball.play_game
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhaoliu/Desktop/google-football/gfootball/play_game.py", line 18, in <module>
    from gfootball.env import football_env
  File "/home/zhaoliu/Desktop/google-football/gfootball/env/__init__.py", line 24, in <module>
    from gfootball.env import football_env
  File "/home/zhaoliu/Desktop/google-football/gfootball/env/football_env.py", line 27, in <module>
    from gfootball.env import football_action_set
  File "/home/zhaoliu/Desktop/google-football/gfootball/env/football_action_set.py", line 25, in <module>
    from gfootball_engine import e_BackendAction
ImportError: cannot import name 'e_BackendAction'

pip version 18.1

I've compiled it in Ubuntu 18.04.2, but I can not run it.

**Comment by qiyuangong** [comment]
Seems like Python cannot find modules in gfootball_engine, which is implemented in C++. Do other examples raise the same error message?

**Comment by lezard618** [comment]
Yes, all the examples have the same error.

**Comment by zajaczajac** [comment]
What command did you use to install the environment? (from pypi or local directory?)
Did you make sure that there was no errors during installation like "Google Research Football compilation failed"?

**Comment by lezard618** [comment]
pip3 install .[tf_cpu] --process-dependency-links

There was a error during installation.
But when I installed it again, the error was gone.
How can I reinstall it again?

**Comment by zajaczajac** [comment]
As apparently compilation of C++ code fails, can you please do the following?:
- get fresh clone of the repo
- go to third_party/gfootball_engine
- run `cmake . && make -j10`
- paste the output

**Comment by lezard618** [comment]
I reinstalled Ubuntu and all other things.
I can run the examples now.
Maybe there was something wrong with the version of a tool.
