### ISSUE TITLE
ImportError: /lib/x86_64-linux-gnu/libwayland-client.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0

### ISSUE THREAD

**Issue by qq591822071** [google-research/football#373]
when I run python3 -m gfootball.play_game --action_set=full
It shows:
Traceback (most recent call last):
  File "/home/yuechao/anaconda3/envs/grf/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/yuechao/anaconda3/envs/grf/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/yuechao/anaconda3/envs/grf/lib/python3.9/site-packages/gfootball/__init__.py", line 17, in <module>
    from gfootball.env import scenario_builder
  File "/home/yuechao/anaconda3/envs/grf/lib/python3.9/site-packages/gfootball/env/__init__.py", line 21, in <module>
    from gfootball.env import config
  File "/home/yuechao/anaconda3/envs/grf/lib/python3.9/site-packages/gfootball/env/config.py", line 27, in <module>
    import gfootball_engine as libgame
  File "/home/yuechao/anaconda3/envs/grf/lib/python3.9/site-packages/gfootball_engine/__init__.py", line 43, in <module>
    from _gameplayfootball import *
ImportError: /lib/x86_64-linux-gnu/libwayland-client.so.0: undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0

**Comment by Marroh** [comment]
I have the same problem. Have you solved it?

**Comment by qq591822071** [comment]
> I have the same problem. Have you solved it?

It's been a while, so I'm not very clear about the method. Most probably, it was solved by modifying the soft link of libffi.so.7 or reinstalling Linux.

**Comment by qiaodan-cuhk** [comment]
The problem is caused by the wrong dynamic library environment variable. To solve this, you can try to add libffi.so.7 into lib envs. Try the following instructions below on Ubuntu.

```locate libffi.so.7```
-> you may see something like "/usr/lib/x86_64-linux-gnu/libffi.so.7  /usr/lib/x86_64-linux-gnu/libffi.so.7.1.0". Then add them into env variables.
```export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libffi.so.7```
```echo $LD_PRELOAD```
-> you may see something like ```/usr/lib/x86_64-linux-gnu/libffi.so.7``` to show the env variable has been successfully set. Then you can run grf with
```python3 -m gfootball.play_game --action_set=full --render=False```
-> See something like ```Episode reward: -2.00 score: [0, 2], steps: 3001, FPS: 138.2, gameFPS: 153.0``` means that it works.
