### ISSUE TITLE
Example execution error

### ISSUE THREAD

**Issue by opocaj92** [google-research/football#386]
Hi everyone,
I've just installed the library in a fresh Python3 virtual environment, and everything went fine. However, when I try to run the example command `python3 -m gfootball.play_game --action_set=full` to validate my installation, I get the following error:

`
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/jacopo/PythonEnvs/marl_py38/lib/python3.8/site-packages/gfootball/__init__.py", line 17, in <module>
    from gfootball.env import scenario_builder
  File "/home/jacopo/PythonEnvs/marl_py38/lib/python3.8/site-packages/gfootball/env/__init__.py", line 21, in <module>
    from gfootball.env import config
  File "/home/jacopo/PythonEnvs/marl_py38/lib/python3.8/site-packages/gfootball/env/config.py", line 27, in <module>
    import gfootball_engine as libgame
  File "/home/jacopo/PythonEnvs/marl_py38/lib/python3.8/site-packages/gfootball_engine/__init__.py", line 43, in <module>
    from _gameplayfootball import *
ImportError: /home/jacopo/PythonEnvs/marl_py38/lib/python3.8/site-packages/gfootball_engine/_gameplayfootball.so: undefined symbol: _ZN5boost10filesystem6detail28directory_iterator_constructERNS0_18directory_iteratorERKNS0_4pathEPNS_6system10error_codeE
`
How can I fix it? Anyone ever experienced it before?

**Comment by Toandinh1** [comment]
> Following from this, when tried to do this again from scratch (this time inside a Docker image), I get the following:
> 
> `Traceback (most recent call last): File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details __import__(pkg_name) File "/usr/local/lib/python3.8/dist-packages/gfootball/__init__.py", line 17, in <module> from gfootball.env import scenario_builder File "/usr/local/lib/python3.8/dist-packages/gfootball/env/__init__.py", line 21, in <module> from gfootball.env import config File "/usr/local/lib/python3.8/dist-packages/gfootball/env/config.py", line 27, in <module> import gfootball_engine as libgame File "/usr/local/lib/python3.8/dist-packages/gfootball_engine/__init__.py", line 43, in <module> from _gameplayfootball import * SystemError: initialization of _gameplayfootball raised unreported exception`
> 
> Anyone has any idea why this is happening?
Did u solve it? can u guide me?

**Comment by opocaj92** [comment]
@Toandinh1 I still have the same issues unfortunately... All I managed to do is to get it to work correctly using the [documented Docker image](https://github.com/google-research/football/blob/master/gfootball/doc/docker.md). But all the other things I tried still failed, including incorporating the installation process of their Docker image inside a personalized image, or replicating the same steps within a fresh `venv` outside of Docker.
