### ISSUE TITLE
Error when Running experiments and Playing game yourself

### ISSUE THREAD

**Issue by ZechenLiu** [google-research/football#46]
Could you please help me solve the AttributeError: 'tuple' object has no attribute 'name'?

> Running experiments

root@lzc-virtual-machine:/home/lzc/football# python3 -m gfootball.examples.run_ppo2 --level=academy_empty_goal_close
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/lzc/football/gfootball/__init__.py", line 23, in <module>
    for env_name in scenario_builder.all_scenarios():
  File "/home/lzc/football/gfootball/env/scenario_builder.py", line 37, in all_scenarios
    return [m.name for m in pkgutil.iter_modules([path])]
  File "/home/lzc/football/gfootball/env/scenario_builder.py", line 37, in <listcomp>
    return [m.name for m in pkgutil.iter_modules([path])]
AttributeError: 'tuple' object has no attribute 'name'

> Playing game yourself

root@lzc-virtual-machine:/home/lzc/football# python3 -m gfootball.play_game
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.5/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/lzc/football/gfootball/__init__.py", line 23, in <module>
    for env_name in scenario_builder.all_scenarios():
  File "/home/lzc/football/gfootball/env/scenario_builder.py", line 37, in all_scenarios
    return [m.name for m in pkgutil.iter_modules([path])]
  File "/home/lzc/football/gfootball/env/scenario_builder.py", line 37, in <listcomp>
    return [m.name for m in pkgutil.iter_modules([path])]
AttributeError: 'tuple' object has no attribute 'name'

` @qstanczyk

**Comment by qstanczyk** [comment]
This issue is due to Python version, between Python 3.5 and Python 3.6 there was a change in pkgutil API which we use:
https://docs.python.org/3.6/library/pkgutil.html#pkgutil.iter_modules
https://docs.python.org/3.5/library/pkgutil.html#pkgutil.iter_modules

You can work around it by changing

> return [m.name for m in pkgutil.iter_modules([path])]

to:

> return [m[2] for m in pkgutil.iter_modules([path])]

In gfootball/env/scenario_builder.py

**Comment by qstanczyk** [comment]
I have just pushed a new version with the workaround to the problem, so alternatively you can just sync to head.

**Comment by ZechenLiu** [comment]
I have solved issue#46. Many thanks for your help.


| |
刘泽辰
|
|
邮箱：15611877789@163.com
|

签名由 网易邮箱大师 定制

On 07/23/2019 15:31, qstanczyk wrote:

Closed #46.
