### ISSUE TITLE
Bug: Rendering frames from dump file with render_dump.py

### ISSUE THREAD

**Issue by alexander3605** [google-research/football#48]
I have some dump files (**with no `frame` saved**) and I am trying to render the frames. <br />
I tried to use the script `render_dump.py` but I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/alessandroserena/.local/lib/python3.6/site-packages/gfootball/render_dump.py", line 43, in <module>
    app.run(main)
  File "/home/alessandroserena/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/alessandroserena/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/alessandroserena/.local/lib/python3.6/site-packages/gfootball/render_dump.py", line 40, in main
    processor.write_dump('episode_done')
  File "/home/alessandroserena/.local/lib/python3.6/site-packages/gfootball/env/observation_processor.py", line 381, in write_dump
    self.process_pending_dumps(True)
  File "/home/alessandroserena/.local/lib/python3.6/site-packages/gfootball/env/observation_processor.py", line 393, in process_pending_dumps
    self._config)
  File "/home/alessandroserena/.local/lib/python3.6/site-packages/gfootball/env/observation_processor.py", line 163, in write_dump
    frame = frame[..., ::-1]
TypeError: string indices must be integers
I0725 16:55:57.314935 140179372074816 observation_processor.py:390] Start dump episode_done
Exception ignored in: <bound method ObservationProcessor.__del__ of <gfootball.env.observation_processor.ObservationProcessor object at 0x7f7dd0174048>>
Traceback (most recent call last):
  File "/home/alessandroserena/.local/lib/python3.6/site-packages/gfootball/env/observation_processor.py", line 320, in __del__
    self.process_pending_dumps(True)
  File "/home/alessandroserena/.local/lib/python3.6/site-packages/gfootball/env/observation_processor.py", line 393, in process_pending_dumps
    self._config)
  File "/home/alessandroserena/.local/lib/python3.6/site-packages/gfootball/env/observation_processor.py", line 163, in write_dump
    frame = frame[..., ::-1]
TypeError: string indices must be integers
```

After a closer inspection I have found out that this error occurs because `frame` is set to the string `'deleted'` and the code therefore fails because it is expecting a pixel matrix. This looks like a loop to me since the script that is supposed to generate the frames expects the frames to be there already.

**Comment by alexander3605** [comment]
**Update:** is `render_dump.py` meant to generate the frames? Or, is its purpose only to generate the `.avi` file when the frames are already present?

**Comment by qstanczyk** [comment]
If you want to render video from a dump you should use replay.py script.
render_dump.py was supposed for converting dumps into visual version with "fake" game rendering, but needs a small fix to not fail on the "deleted" string.

**Comment by alexander3605** [comment]
Thanks for your answer :)
What do you mean as "fake" game rendering? 
If the fix for the "deleted" string is applied, would `render_dump.py` be able to generate the frames when these are not already in the dump? Or which kind of _visual version_ would it create?

**Comment by qstanczyk** [comment]
It would render 2D field with dots representing players, so it is easier to interpret than the row dump, but there will be no real game rendering. To see rendering you need to use replay script.
