### ISSUE TITLE
TypeError running random agent

### ISSUE THREAD

**Issue by hyren** [google-research/football#56]
I have just cloned the latest repo and built from scratch, but I am still getting this error msg.
```
Traceback (most recent call last):
  File "football.py", line 17, in <module>
    e.reset()
  File "/home/hongyu/anaconda3/envs/pearl/lib/python3.5/site-packages/gym/core.py", line 327, in reset
    return self.env.reset()
  File "/home/hongyu/anaconda3/envs/pearl/lib/python3.5/site-packages/gym/core.py", line 317, in reset
    observation = self.env.reset(**kwargs)
  File "/home/hongyu/anaconda3/envs/pearl/lib/python3.5/site-packages/gym/core.py", line 318, in reset
    return self.observation(observation)
  File "/home/hongyu/anaconda3/envs/pearl/lib/python3.5/site-packages/gfootball/env/wrappers.py", line 135, in observation
    frame = obs['frame']
TypeError: list indices must be integers or slices, not str
```
My code is listed below:
```
import gfootball.env as football_env
import os
os.environ["MESA_GL_VERSION_OVERRIDE"]='3.2'   
os.environ["MESA_GLSL_VERSION_OVERRIDE"]='150'

e = football_env.create_environment(
	env_name='academy_empty_goal_close', 
	representation='pixels', 
	# rewards='scoring,checkpoints',
	render=True
)

for i in range(10000):
	e.reset()
	done = False
	while not done:
		_, _, done, _ = e.step(e.action_space.sample())
		# e.render()
```
I feel the error is caused by the incompatibility between different representations and render functions.
I only encountered this error when the representation is `pixels` or `pixels_gray`. `extracted` and `simple115` works.

**Comment by AntonRaichuk** [comment]
The fix should be released later today

**Comment by qstanczyk** [comment]
v1.3 release (just pushed) has a fix to this problem.
