### ISSUE TITLE
gfootball (1.2) -- TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by ZhangRui111** [google-research/football#57]
## Version of my tensorflow and gfootball
- tensorboard (1.14.0)
- tensorflow-estimator (1.14.0)
- tensorflow-gpu (1.14.0)
- gfootball (1.2)

What's more, I installed gfootball by
- `git clone https://github.com/google-research/football.git`
- `cd football`
- `pip3 install .[tf_gpu]`

Then update it to version 1.2 by
- `pip3 install gfootball -U`

## My code that involving all parameters
```
import gfootball.env as football_env
import numpy as np
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = '3'
os.environ["CUDA_VISIBLE_DEVICES"] = '0'


def create_single_football_env(seed):
    """Creates gfootball environment."""
    env = football_env.create_environment(
        env_name='academy_empty_goal_close',
        stacked=False,
        representation='pixels',
        rewards='scoring',
        logdir='./logs/',
        enable_goal_videos=False,
        enable_full_episode_videos=False,
        render=True,
    )
    return env


def main():
    gfenv = create_single_football_env(seed=0)
    for i in range(100):
        gfenv.reset()
        while True:
            act = np.random.random_integers(0, 20)
            obs_, r, done, info = gfenv.step(act)
            print("action: {0} | reward: {1} | done: {2}".format(act, r, done))
            if done:
                break


if __name__ == '__main__':
    main()
```
## Error log info when the **representation='pixels'** or **representation='pixels_gray'**
```
Traceback (most recent call last):
  File "/home/rui/Documents/codes/pycharm/gfootballwrap/test.py", line 37, in <module>
    main()
  File "/home/rui/Documents/codes/pycharm/gfootballwrap/test.py", line 27, in main
    gfenv.reset()
  File "/home/rui/.local/lib/python3.5/site-packages/gym/core.py", line 270, in reset
    return self.env.reset(**kwargs)
  File "/home/rui/.local/lib/python3.5/site-packages/gym/core.py", line 257, in reset
    observation = self.env.reset(**kwargs)
  File "/home/rui/.local/lib/python3.5/site-packages/gym/core.py", line 258, in reset
    return self.observation(observation)
  File "/home/rui/.local/lib/python3.5/site-packages/gfootball/env/wrappers.py", line 151, in observation
    frame = obs['frame']
TypeError: list indices must be integers or slices, not str
```
##  Temporary solution
This could be fixed by modifying `*/gfootball/env/wrapper.py`. But I guess this is not a clean fix. Hope this bug could be fixed as soon as possible.

**line 135 in `wrapper.py`**

- original codes:
```
frame = obs['frame']
```
- replaced by:
```
if type(obs) is list:
  if len(obs) == 1:
    obs = obs[0]
  else:
    raise NotImplementedError
frame = obs['frame']
```

**Comment by qstanczyk** [comment]
Thanks for reporting.
v1.3 release (just pushed) has a fix to this problem.
