### ISSUE TITLE
Cannot env.reset() in multi-agent setup.

### ISSUE THREAD

**Issue by julienroy13** [google-research/football#59]
I am unable to `env.reset()` when instantiating a multi-agent version of the environment. I get the following error:

```
Traceback (most recent call last):
  File "foot_error.py", line 28, in <module>
    env.reset()
  File "/home/user1/anaconda3/envs/foot/lib/python3.7/site-packages/gym/core.py", line 258, in reset
    return self.observation(observation)
  File "/home/user1/anaconda3/envs/foot/lib/python3.7/site-packages/gfootball/env/wrappers.py", line 80, in observation
    for a in obs['active']:
TypeError: list indices must be integers or slices, not str
```

Here is a minimal example that triggers the issue. It is based on the multi-agent rllab example.
```
import gfootball.env as football_env
from gfootball.env import observation_preprocessing

def createMultiAgentEnv():
    env = football_env.create_environment(
            env_name='academy_3_vs_1_with_keeper',
            stacked=False,
            representation='simple115',
            rewards='scoring',
            logdir='~/Desktop/test',
            enable_goal_videos=False,
            enable_full_episode_videos=False,
            render=True,
            write_video=False,
            dump_frequency=5,
            number_of_left_players_agent_controls=3,
            number_of_right_players_agent_controls=0,
            enable_sides_swap=False,
            channel_dimensions=(
                observation_preprocessing.SMM_WIDTH,
                observation_preprocessing.SMM_HEIGHT)
        )
    return env

if __name__ == "__main__":
    env = createMultiAgentEnv()
    env.reset()
```

**Comment by AntonRaichuk** [comment]
Please use latest version of the environment code where the issue that you are reporting is already fixed.

**Comment by julienroy13** [comment]
Oh, my apologies. Thanks for the support!
